export const refs = {
  formWrapper: document.querySelector('.hero__form-wrapper'),
  form: document.querySelector('.form'),
  searchBtn: document.querySelector('.form__btn'),
  spinner: document.querySelector('.spinner'),
  result: document.querySelector('.result'),
  closeResultBtn: document.querySelector('[data-close]'),
  nick: document.querySelector('[data-nick]'),
  avatar: document.querySelector('[data-avatar]'),
  name: document.querySelector('[data-name]'),
  icon: document.querySelector('[data-icon]'),
  status: document.querySelector('[data-status]'),
  location: document.querySelector('[data-location]'),
  following: document.querySelector('[data-following]'),
  followers: document.querySelector('[data-followers]'),
  years: document.querySelector('[data-years]'),
  months: document.querySelector('[data-months]'),
  days: document.querySelector('[data-days]'),
  hours: document.querySelector('[data-hours]'),
  minutes: document.querySelector('[data-minutes]'),
  seconds: document.querySelector('[data-seconds]'),
  members: document.querySelector('[data-members]'),
  repos: document.querySelector('[data-repos]'),
};
